name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      # Build main site (in ./main)
      - name: Install and build main
        working-directory: ./main
        run: |
          npm install
          npm run build

      # Clone and build danmaku3d-demo
      - name: Clone and build danmaku3d-demo
        run: |
          git clone https://github.com/Commute773/danmaku3d-demo.git
          cd danmaku3d-demo
          npm install --legacy-peer-deps
          CI=false npm run build
          cd ..

      # Clone and build wordfind-vr
      - name: Clone and build wordfind-vr
        run: |
          git clone https://github.com/Commute773/wordfind-vr.git
          cd wordfind-vr
          npm install
          npm run build
          cd ..

      # Assemble the deploy folder
      - name: Assemble deploy directory
        run: |
          mkdir -p deploy
          # 1. Copy danmaku3d to root
          cp -r danmaku3d-demo/build/* deploy/ || true
          # 2. Save original index.html
          mkdir -p deploy/_temp
          cp danmaku3d-demo/build/index.html deploy/_temp/danmaku3d-index.html || true
          # 3. Merge main site into root (may overwrite index.html etc.)
          cp -r main/dist/* deploy/ || true
          # 4. Restore original danmaku3d index.html to /menu
          mkdir -p deploy/menu
          cp deploy/_temp/danmaku3d-index.html deploy/menu/index.html || true
          # Cleanup
          rm -rf deploy/_temp
          # Prevent indexing
          echo -e "User-agent: *\nDisallow: /" > deploy/robots.txt
          # Debug output
          apt-get update && apt-get install tree -y
          tree deploy


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
